import "./components/pages/Dashboard.js";
import { errorService } from "./lib/error-service.js";
import "./components/pages/WorkerDemo.js";
import "./components/Notification.js";
import "./components/pages/HomePage.js";
import "./components/pages/RepoSearch.js";
import { registerApp } from "./app/App.js";
import { registerRoute } from "./components/route/route.js";
registerRoute();
registerApp();
